### ISSUE TITLE
hello i bought stable diffusion from microsoft store and cant run it please help

### ISSUE THREAD

**Issue by victorwijayakusuma** [PhytoEpidemic/stable-diffusion-webui-installation-manager#1]
RuntimeError: Couldn't install torch.
Command: "D:\system\python\python.exe" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Error code: 2
Press any key to continue . . .

**Comment by PhytoEpidemic** [comment]
> RuntimeError: Couldn't install torch.
> Command: "D:\system\python\python.exe" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
> Error code: 2
> Press any key to continue . . .

I can run some tests to try and replicate the issue. I think it might be because you choose a drive instead of a folder to install it in. Try making a new folder inside of your D drive and choose that folder to install to.

**Comment by victorwijayakusuma** [comment]
Hello thank you for your help, I did add a folder inside my D as you said
And now its like this


***@***.***

Please help


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PhytoEpidemic** [comment]
This may be a compatibility issue or something is strange about your system. The launcher is working as expected but the webui seems to not like your setup. I found the issue in the repository but unfortunately the only real solution to try is restarting your computer and installing to a new folder again. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4412
